# snpEff_4.3t
# 20180803

FROM centos:yum-jdk

MAINTAINER lrtao2010

RUN mkdir /usr/local/snpeff
ADD snpEff_latest_core.tar.gz /usr/local/snpeff 

CMD ["/bin/bash"]
#/usr/local/snpeff/clinEff/ClinEff.jar
#/usr/local/snpeff/snpEff/SnpSift.jar
#/usr/local/snpeff/snpEff/snpEff.jar
